image: 
  file: .gitpod.Dockerfile
tasks:
  - init: |
     pip3 install --no-cache-dir  -r requirements.txt -r requirements.askar.txt -r requirements.bbs.txt -r requirements.dev.txt
     pip install -r requirements.txt

vscode:
  extensions:
    - mhutchie.git-graph
    - littlefoxteam.vscode-python-test-adapter
    - eamodio.gitlens